[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_post_source='''
let g:syntastic_mode_map = { 'mode': 'passive',
            \ 'active_filetypes': ['ruby', 'go'] }
let g:syntastic_ruby_checkers = ['rubocop']
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/open-browser.vim'
